version: '2'

services:
  mydb:
    image: mysql
    volumes:
      - ./mysql/runtime:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD
    networks:
      - back
    restart: unless-stopped
  app:
    image: piwik:fpm
    links:
      - mydb
    volumes:
      - ./config:/var/www/html/config
    networks:
      - back
    restart: unless-stopped
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    links:
      - app
    volumes_from:
      - app
    environment:
      - VIRTUAL_HOST
    networks:
      - back
      - lb_web
    ports:
      - "8084:80"
    restart: unless-stopped
  cron:
    image: piwik:fpm
    links:
      - mydb
    volumes_from:
      - app
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      while /bin/true; do
        su -s "/bin/bash" -c "/usr/local/bin/php /var/www/html/console core:archive" www-data
        sleep 3600
      done
      EOF'
    networks:
      - back
    restart: unless-stopped

networks:
  lb_web:
    external: true
  back:
    driver: bridge